// Generert automatisk av konverter_anlegg.py - rediger ikkje direkte.
// Oppdater i stedet anleggsdata_2.xlsx og køyr scriptet på nytt.
const anleggData = [
  {
    "Navn": "Aurland barne - og ungdomsskule - ballbinge",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Anlegg for ballaktivitet",
    "Anleggstype": "Ballbinge",
    "Byggeår": 2004,
    "Siste ombyggingsår": 2005,
    "Lengdegrad": 7.196079,
    "Breddegrad": 60.902799,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Aurland barne- og ungdomsskule aktivitetspark",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Mindre utendørsanlegg",
    "Anleggstype": "Flerbruksområde (ute)",
    "Byggeår": 2019,
    "Siste ombyggingsår": 2023,
    "Lengdegrad": 7.196630461943414,
    "Breddegrad": 60.904218328985266,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Aurland idretts og samfunnshus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Kulturarena",
    "Anleggstype": "Flerbrukslokale for kultur",
    "Byggeår": 1979,
    "Siste ombyggingsår": 1980,
    "Lengdegrad": 7.194951,
    "Breddegrad": 60.902856,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Aurland idretts og samfunnshus - svømmehallen",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Svømme- og stupeanlegg",
    "Anleggstype": "Trenings-/konkurransebasseng (inne)",
    "Byggeår": 1979,
    "Siste ombyggingsår": 2022,
    "Lengdegrad": 7.195197,
    "Breddegrad": 60.90276,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Aurland stadion - Aurlandshallen",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Idrettshaller og aktivitetssaler",
    "Anleggstype": "Idrettshall",
    "Byggeår": 2009,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.194633,
    "Breddegrad": 60.902286,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Aurland stadion - idrettshus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Idrettshus og servicebygg",
    "Anleggstype": "Idrettshus",
    "Byggeår": 1985,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.196858,
    "Breddegrad": 60.904022,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND IDRETTSLAG",
    "Planlagt": false
  },
  {
    "Navn": "Aurland stadion - kunstgras",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Fotballanlegg",
    "Anleggstype": "Fotballbane kunstgress",
    "Byggeår": 1985,
    "Siste ombyggingsår": 2025,
    "Lengdegrad": 7.200434422737751,
    "Breddegrad": 60.902525051937246,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Aurland stadion Sykkelbane",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Sykkelanlegg",
    "Anleggstype": "BMX-bane",
    "Byggeår": 2005,
    "Siste ombyggingsår": 2004,
    "Lengdegrad": 7.195194,
    "Breddegrad": 60.902482,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Aurland stadion-friidrettsbane",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Friidrettsanlegg",
    "Anleggstype": "Friidrettsstadion kunststoff",
    "Byggeår": 1986,
    "Siste ombyggingsår": 1952,
    "Lengdegrad": 7.196228,
    "Breddegrad": 60.90343,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Aurlandsdalen turisthytte Østerbø gnr 24 bnr 21",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Overnattingshytte",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.504567121405785,
    "Breddegrad": 60.82839018923273,
    "Eier": "DEN NORSKE TURISTFORENING OSLO OG OMEGN",
    "Drifter": "DEN NORSKE TURISTFORENING OSLO OG OMEGN",
    "Planlagt": false
  },
  {
    "Navn": "Aurlandshallen, innandørs skytebane",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Skyteanlegg",
    "Anleggstype": "Skytebane (inne)",
    "Byggeår": 2009,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.194633,
    "Breddegrad": 60.902286,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND SKYTTARLAG",
    "Planlagt": false
  },
  {
    "Navn": "Aurlandshallen, klatrevegg",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Klatreanlegg",
    "Anleggstype": "Klatre/buldrevegg (inne)",
    "Byggeår": 2009,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.194633,
    "Breddegrad": 60.902286,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Ball og klatrevegg ABU",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Mindre utendørsanlegg",
    "Anleggstype": "Flerbruksområde (ute)",
    "Byggeår": 2022,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.19649184560974,
    "Breddegrad": 60.903521833101244,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Brekkefossen tursti",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Tursti",
    "Byggeår": 1947,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.095442,
    "Breddegrad": 60.851839,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Flåm samfunnshus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Kulturarena",
    "Anleggstype": "Flerbrukslokale for kultur",
    "Byggeår": 1954,
    "Siste ombyggingsår": 1954,
    "Lengdegrad": 7.11004,
    "Breddegrad": 60.856203,
    "Eier": "Flåm Samfunnshus",
    "Drifter": "Flåm Samfunnshus",
    "Planlagt": false
  },
  {
    "Navn": "Flåm stadion - fotballbane",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Fotballanlegg",
    "Anleggstype": "Fotballbane grus",
    "Byggeår": 1992,
    "Siste ombyggingsår": 1994,
    "Lengdegrad": 7.112755,
    "Breddegrad": 60.864494,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Kongshelleren",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Overnattingshytte",
    "Byggeår": 1980,
    "Siste ombyggingsår": 2004,
    "Lengdegrad": 7.701476,
    "Breddegrad": 60.777157,
    "Eier": "DEN NORSKE TURISTFORENING OSLO OG OMEGN",
    "Drifter": "AURLAND FJELLSTYRE",
    "Planlagt": false
  },
  {
    "Navn": "Leikvollen nærmiljøanlegg",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Mindre utendørsanlegg",
    "Anleggstype": "Flerbruksområde (ute)",
    "Byggeår": 2016,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.335446,
    "Breddegrad": 60.875089,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "VASSBYGDI UNGDOMSLAG",
    "Planlagt": false
  },
  {
    "Navn": "Lovi skytebane , 200 m",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Skyteanlegg",
    "Anleggstype": "Riflebane (ute)",
    "Byggeår": 1991,
    "Siste ombyggingsår": 2024,
    "Lengdegrad": 7.245886,
    "Breddegrad": 60.878842,
    "Eier": "AURLAND SKYTTARLAG",
    "Drifter": "AURLAND SKYTTARLAG",
    "Planlagt": false
  },
  {
    "Navn": "Lovi skytebane, 100m og 300m",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Skyteanlegg",
    "Anleggstype": "Riflebane (ute)",
    "Byggeår": 1972,
    "Siste ombyggingsår": 2004,
    "Lengdegrad": 7.245832059829059,
    "Breddegrad": 60.878960907483716,
    "Eier": "AURLAND SKYTTARLAG",
    "Drifter": "AURLAND SKYTTARLAG",
    "Planlagt": false
  },
  {
    "Navn": "Lovi skytebane, skyttarhus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Idrettshus og servicebygg",
    "Anleggstype": "Idrettshus",
    "Byggeår": 1972,
    "Siste ombyggingsår": 2024,
    "Lengdegrad": 7.245914,
    "Breddegrad": 60.878995,
    "Eier": "AURLAND SKYTTARLAG",
    "Drifter": "AURLAND SKYTTARLAG",
    "Planlagt": false
  },
  {
    "Navn": "Rallarvegen - turveg",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Tursti",
    "Byggeår": 1947,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.119838,
    "Breddegrad": 60.730476,
    "Eier": "NSB EIENDOM AS",
    "Drifter": "NSB EIENDOM AS",
    "Planlagt": false
  },
  {
    "Navn": "Skjerping ballbinge",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Anlegg for ballaktivitet",
    "Anleggstype": "Ballbinge",
    "Byggeår": 2003,
    "Siste ombyggingsår": 2003,
    "Lengdegrad": 6.804928,
    "Breddegrad": 60.858959,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "NÆRØY VEL",
    "Planlagt": false
  },
  {
    "Navn": "Stemmerdalen turveg for rullestolbrukarar",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Turvei",
    "Byggeår": 2003,
    "Siste ombyggingsår": 2003,
    "Lengdegrad": 7.57669,
    "Breddegrad": 60.778146,
    "Eier": "AURLAND FJELLSTYRE",
    "Drifter": "AURLAND FJELLSTYRE",
    "Planlagt": false
  },
  {
    "Navn": "Stemmerdalen-Østerbø",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Tursti",
    "Byggeår": 1947,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.581244,
    "Breddegrad": 60.779406,
    "Eier": "DEN NORSKE TURISTFORENING",
    "Drifter": "DEN NORSKE TURISTFORENING",
    "Planlagt": false
  },
  {
    "Navn": "Trudvang ungdomshus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Kulturarena",
    "Anleggstype": "Flerbrukslokale for kultur",
    "Byggeår": 1914,
    "Siste ombyggingsår": 1993,
    "Lengdegrad": 7.190167,
    "Breddegrad": 60.905611,
    "Eier": "Aurland Ungdomshus",
    "Drifter": "Aurland Ungdomshus",
    "Planlagt": false
  },
  {
    "Navn": "Tusenårsstaden på Rygg - leikeplass",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Anlegg for ballaktivitet",
    "Anleggstype": "Liten balløkke/-bane",
    "Byggeår": 2006,
    "Siste ombyggingsår": 2006,
    "Lengdegrad": 7.193113,
    "Breddegrad": 60.90733,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  },
  {
    "Navn": "Undredal sentrum - Stokko",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Tursti",
    "Byggeår": 2021,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.105090528589888,
    "Breddegrad": 60.95076760136471,
    "Eier": "UNDREDAL GRENDALAG",
    "Drifter": "UNDREDAL GRENDALAG",
    "Planlagt": false
  },
  {
    "Navn": "Undredal ungdomshus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Kulturarena",
    "Anleggstype": "Flerbrukslokale for kultur",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.101255870891792,
    "Breddegrad": 60.94924943696537,
    "Eier": "UNDREDAL UNGDOMSLAG",
    "Drifter": "UNDREDAL UNGDOMSLAG",
    "Planlagt": false
  },
  {
    "Navn": "Vinjaåsen Dagsturhytte",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Dagsturhytte",
    "Byggeår": 2018,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.202310562133789,
    "Breddegrad": 60.90702841649545,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false
  }
];
