// Generert automatisk av konverter_anlegg.py - rediger ikkje direkte.
// Oppdater i stedet anleggsdata_2.xlsx og køyr scriptet på nytt.
const anleggData = [
  {
    "Navn": "Aurland barne - og ungdomsskule - ballbinge",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Anlegg for ballaktivitet",
    "Anleggstype": "Ballbinge",
    "Byggeår": 2004,
    "Siste ombyggingsår": 2005,
    "Lengdegrad": 7.196079,
    "Breddegrad": 60.902799,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/abu.jpg"
  },
  {
    "Navn": "Aurland barne- og ungdomsskule aktivitetspark",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Lekeanlegg",
    "Anleggstype": "Flerbruksområde (ute)",
    "Byggeår": 2019,
    "Siste ombyggingsår": 2023,
    "Lengdegrad": 7.19663046194341,
    "Breddegrad": 60.9042183289853,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Aurland idretts og samfunnshus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Kulturarena",
    "Anleggstype": "Flerbrukslokale for kultur",
    "Byggeår": 1979,
    "Siste ombyggingsår": 1980,
    "Lengdegrad": 7.194951,
    "Breddegrad": 60.902856,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/AIS.jpg"
  },
  {
    "Navn": "Aurland idretts og samfunnshus - svømmehallen",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Svømme- og stupeanlegg",
    "Anleggstype": "Trenings-/konkurransebasseng (inne)",
    "Byggeår": 1979,
    "Siste ombyggingsår": 2022,
    "Lengdegrad": 7.195197,
    "Breddegrad": 60.90276,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Aurland stadion - Aurlandshallen",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Idrettshaller og aktivitetssaler",
    "Anleggstype": "Idrettshall",
    "Byggeår": 2009,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.194633,
    "Breddegrad": 60.902286,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/aurlandshallen.jpg"
  },
  {
    "Navn": "Aurland stadion - idrettshus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Idrettshus og servicebygg",
    "Anleggstype": "Idrettshus",
    "Byggeår": 1985,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.19657341926558,
    "Breddegrad": 60.9043598902674,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND IDRETTSLAG",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/idrett.jpg"
  },
  {
    "Navn": "Aurland stadion - kunstgras",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Fotballanlegg",
    "Anleggstype": "Fotballbane kunstgress",
    "Byggeår": 1985,
    "Siste ombyggingsår": 2025,
    "Lengdegrad": 7.19552376914535,
    "Breddegrad": 60.9039986699071,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Aurland stadion Sykkelbane",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Sykkelanlegg",
    "Anleggstype": "BMX-bane",
    "Byggeår": 2005,
    "Siste ombyggingsår": 2026,
    "Lengdegrad": 7.195194,
    "Breddegrad": 60.902482,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/pumptrack.jpg"
  },
  {
    "Navn": "Aurland stadion-friidrettsbane",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Friidrettsanlegg",
    "Anleggstype": "Friidrettsstadion kunststoff",
    "Byggeår": 1986,
    "Siste ombyggingsår": 1952,
    "Lengdegrad": 7.196228,
    "Breddegrad": 60.90343,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/lopebane.jpg"
  },
  {
    "Navn": "Aurlandsdalen turisthytte Østerbø gnr 24 bnr 21",
    "Anleggsklasse": "Friluftslivsanlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Overnattingshytte",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.50456712140579,
    "Breddegrad": 60.8283901892327,
    "Eier": "DEN NORSKE TURISTFORENING OSLO OG OMEGN",
    "Drifter": "DEN NORSKE TURISTFORENING OSLO OG OMEGN",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/ostebo.jpg"
  },
  {
    "Navn": "Aurlandshallen, innandørs skytebane",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Skyteanlegg",
    "Anleggstype": "Skytebane (inne)",
    "Byggeår": 2009,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.194633,
    "Breddegrad": 60.902286,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND SKYTTARLAG",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/lovi.jpg"
  },
  {
    "Navn": "Aurlandshallen, klatrevegg",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Klatreanlegg",
    "Anleggstype": "Klatre/buldrevegg (inne)",
    "Byggeår": 2009,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.194633,
    "Breddegrad": 60.902286,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/klatrevegg.jpg"
  },
  {
    "Navn": "Ball og klatrevegg ABU",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Mindre utendørsanlegg",
    "Anleggstype": "Flerbruksområde (ute)",
    "Byggeår": 2022,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.19649184560974,
    "Breddegrad": 60.9035218331012,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Brekkefossen tursti",
    "Anleggsklasse": "Friluftslivsanlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Tursti",
    "Byggeår": 1947,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.095442,
    "Breddegrad": 60.851839,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/brekkefossen.jpg"
  },
  {
    "Navn": "Flåm samfunnshus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Kulturarena",
    "Anleggstype": "Flerbrukslokale for kultur",
    "Byggeår": 1954,
    "Siste ombyggingsår": 1954,
    "Lengdegrad": 7.11004,
    "Breddegrad": 60.856203,
    "Eier": "Flåm Samfunnshus",
    "Drifter": "Flåm Samfunnshus",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/flam_Samf.jpg"
  },
  {
    "Navn": "Flåm strandvolleyball",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Strandvolletball",
    "Anleggstype": "Strandvolletball",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.11684508995846,
    "Breddegrad": 60.8653741425954,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "Fin standard",
    "Bilde": "bilder/volleyball.jpg"
  },
  {
    "Navn": "Kongshelleren",
    "Anleggsklasse": "Friluftslivsanlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Overnattingshytte",
    "Byggeår": 1980,
    "Siste ombyggingsår": 2004,
    "Lengdegrad": 7.701476,
    "Breddegrad": 60.777157,
    "Eier": "DEN NORSKE TURISTFORENING OSLO OG OMEGN",
    "Drifter": "AURLAND FJELLSTYRE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/kongshelleren.jpg"
  },
  {
    "Navn": "Leikvollen nærmiljøanlegg",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Mindre utendørsanlegg",
    "Anleggstype": "Flerbruksområde (ute)",
    "Byggeår": 2016,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.335446,
    "Breddegrad": 60.875089,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "VASSBYGDI UNGDOMSLAG",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Lovi skytebane , 200 m",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Skyteanlegg",
    "Anleggstype": "Riflebane (ute)",
    "Byggeår": 1991,
    "Siste ombyggingsår": 2024,
    "Lengdegrad": 7.245886,
    "Breddegrad": 60.878842,
    "Eier": "AURLAND SKYTTARLAG",
    "Drifter": "AURLAND SKYTTARLAG",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/lovi.jpg"
  },
  {
    "Navn": "Lovi skytebane, 100m og 300m",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Skyteanlegg",
    "Anleggstype": "Riflebane (ute)",
    "Byggeår": 1972,
    "Siste ombyggingsår": 2004,
    "Lengdegrad": 7.24583205982906,
    "Breddegrad": 60.8789609074837,
    "Eier": "AURLAND SKYTTARLAG",
    "Drifter": "AURLAND SKYTTARLAG",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/lovi.jpg"
  },
  {
    "Navn": "Lovi skytebane, skyttarhus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Idrettshus og servicebygg",
    "Anleggstype": "Idrettshus",
    "Byggeår": 1972,
    "Siste ombyggingsår": 2024,
    "Lengdegrad": 7.245914,
    "Breddegrad": 60.878995,
    "Eier": "AURLAND SKYTTARLAG",
    "Drifter": "AURLAND SKYTTARLAG",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/lovi.jpg"
  },
  {
    "Navn": "Rallarvegen - turveg",
    "Anleggsklasse": "Friluftslivsanlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Tursti",
    "Byggeår": 1947,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.119838,
    "Breddegrad": 60.730476,
    "Eier": "NSB EIENDOM AS",
    "Drifter": "NSB EIENDOM AS",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Skjerping ballbinge",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Anlegg for ballaktivitet",
    "Anleggstype": "Ballbinge",
    "Byggeår": 2003,
    "Siste ombyggingsår": 2003,
    "Lengdegrad": 6.804928,
    "Breddegrad": 60.858959,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "NÆRØY VEL",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Stemmerdalen turveg for rullestolbrukarar",
    "Anleggsklasse": "Friluftslivsanlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Turvei",
    "Byggeår": 2003,
    "Siste ombyggingsår": 2003,
    "Lengdegrad": 7.57669,
    "Breddegrad": 60.778146,
    "Eier": "AURLAND FJELLSTYRE",
    "Drifter": "AURLAND FJELLSTYRE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Stemmerdalen-Østerbø",
    "Anleggsklasse": "Friluftslivsanlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Tursti",
    "Byggeår": 1947,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.581244,
    "Breddegrad": 60.779406,
    "Eier": "DEN NORSKE TURISTFORENING",
    "Drifter": "DEN NORSKE TURISTFORENING",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Trudvang ungdomshus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Kulturarena",
    "Anleggstype": "Flerbrukslokale for kultur",
    "Byggeår": 1914,
    "Siste ombyggingsår": 1993,
    "Lengdegrad": 7.190167,
    "Breddegrad": 60.905611,
    "Eier": "Aurland Ungdomshus",
    "Drifter": "Aurland Ungdomshus",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/kino.jpg"
  },
  {
    "Navn": "Tusenårsstaden på Rygg - leikeplass",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Lekeanlegg",
    "Anleggstype": "Liten balløkke/-bane",
    "Byggeår": 2006,
    "Siste ombyggingsår": 2006,
    "Lengdegrad": 7.193113,
    "Breddegrad": 60.90733,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Undredal sentrum - Stokko",
    "Anleggsklasse": "Friluftslivsanlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Tursti",
    "Byggeår": 2021,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.10509052858989,
    "Breddegrad": 60.9507676013647,
    "Eier": "UNDREDAL GRENDALAG",
    "Drifter": "UNDREDAL GRENDALAG",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Undredal ungdomshus",
    "Anleggsklasse": "Ordinært anlegg",
    "Anleggskategori": "Kulturarena",
    "Anleggstype": "Flerbrukslokale for kultur",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.10125587089179,
    "Breddegrad": 60.9492494369654,
    "Eier": "UNDREDAL UNGDOMSLAG",
    "Drifter": "UNDREDAL UNGDOMSLAG",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Vinjaåsen Dagsturhytte",
    "Anleggsklasse": "Friluftslivsanlegg",
    "Anleggskategori": "Friluftslivsanlegg",
    "Anleggstype": "Dagsturhytte",
    "Byggeår": 2018,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.20231056213379,
    "Breddegrad": 60.9070284164955,
    "Eier": "AURLAND KOMMUNE",
    "Drifter": "AURLAND KOMMUNE",
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/dagsturhytta.jpg"
  },
  {
    "Navn": "Paddlebane",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": NaN,
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.11651601971163,
    "Breddegrad": 60.8652383505378,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": true,
    "Kommentar": "Tenkt bygget med volleyballbaner",
    "Bilde": ""
  },
  {
    "Navn": "Tursti SJBS -> Turlielva",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Grussti",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.21925712113263,
    "Breddegrad": 60.8985022453905,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": true,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Badelaguna",
    "Anleggsklasse": "Utendørsanlegg",
    "Anleggskategori": "Badaplass",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18880071366129,
    "Breddegrad": 60.908932359805,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": true,
    "Kommentar": "Her kan med fordel bygges en UU rampe",
    "Bilde": "bilder/badelagune.jpg"
  },
  {
    "Navn": "Grusstak Høydalen",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Grusstak med fotballmål",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.197761857152,
    "Breddegrad": 60.9245215482365,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "Kandidat for ombygging",
    "Bilde": "bilder/Grusstak_Hoydalen.jpg"
  },
  {
    "Navn": "Lekeanlegg TY",
    "Anleggsklasse": "Lekeanlegg",
    "Anleggskategori": "Lekeanlegg",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.19701139875825,
    "Breddegrad": 60.9222480555779,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "Lekeplass, ny type kompan",
    "Bilde": "bilder/lekeplass_Ty.jpg"
  },
  {
    "Navn": "Lekeanlegg Fiskhammar",
    "Anleggsklasse": "Lekeanlegg",
    "Anleggskategori": "Lekeanlegg",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.19668756978342,
    "Breddegrad": 60.9274636419591,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "Lekeplass, ny type kompan",
    "Bilde": "bilder/lekeplass_Fiskehammar.jpg"
  },
  {
    "Navn": "Grusstak Vetleli",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Grusstak med fotballmål",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.19060360186665,
    "Breddegrad": 60.9105804800547,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "Kandidat for ombygging",
    "Bilde": "bilder/grustak_V_HT.jpg"
  },
  {
    "Navn": "Lekeanlegg Ystebøen",
    "Anleggsklasse": "Lekeanlegg",
    "Anleggskategori": "Lekeanlegg",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.19392291089006,
    "Breddegrad": 60.9156084335132,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Haralds Plass",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Grillplass med overbygg",
    "Anleggstype": "Grillplass med overbygg",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.11870999660845,
    "Breddegrad": 60.866188417478,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "mye bruk",
    "Bilde": "bilder/haraldsPlass.jpg"
  },
  {
    "Navn": "Lekeanlegg Flåm sentrum",
    "Anleggsklasse": "Lekeanlegg",
    "Anleggskategori": "Lekeanlegg",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.11766652359794,
    "Breddegrad": 60.8642650667695,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Lekeanlegg Flåm barnehage",
    "Anleggsklasse": "Lekeanlegg",
    "Anleggskategori": "Lekeanlegg i tilknyttning barnehage",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.11108534668775,
    "Breddegrad": 60.8526648279872,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "mye brukt etter stengning, her kan det bli behov for et nytt lekeareal ved nedlegging",
    "Bilde": "bilder/flam_Barnehage.jpg"
  },
  {
    "Navn": "Lekeanlegg",
    "Anleggsklasse": "Lekeanlegg",
    "Anleggskategori": "Lekeanlegg i tilknyttning barnehage",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.11108534668775,
    "Breddegrad": 60.8526648279872,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": true,
    "Kommentar": "Deler av arealet",
    "Bilde": "bilder/flam_Barnehage.jpg"
  },
  {
    "Navn": "Lekeanlegg Gudvangen /v vikinglandsby",
    "Anleggsklasse": "Lekeanlegg",
    "Anleggskategori": "Lekeanlegg",
    "Anleggstype": "Lekeplass",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 6.84359211685879,
    "Breddegrad": 60.8803356115859,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/lek_gudvangen.jpg"
  },
  {
    "Navn": "Grussti langs veien gudvangen",
    "Anleggsklasse": "Friluftslivsanlegg",
    "Anleggskategori": "Grussti",
    "Anleggstype": "Grussti",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 6.84117984338767,
    "Breddegrad": 60.8799357242328,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Utendørs møtested Undredal",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Møtested",
    "Anleggstype": "møtested",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.10545399426301,
    "Breddegrad": 60.9509238797261,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "Her står ei flott geit",
    "Bilde": "bilder/geit_undredal.jpg"
  },
  {
    "Navn": "Nærmiljøanlegg",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Fotballanlegg",
    "Anleggstype": "fotballbane gress",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.17228539150975,
    "Breddegrad": 60.9012713079376,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": true,
    "Kommentar": "Lekeplass, bålplass, fotballmål",
    "Bilde": "bilder/gress.jpg"
  },
  {
    "Navn": "Dissestativ",
    "Anleggsklasse": "Lekeanlegg",
    "Anleggskategori": "Lekeanlegg i tilknyttning Flåm skole",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18572598153121,
    "Breddegrad": 60.9062701158165,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "Enkelt dissestativ. Behov for en oppgradering",
    "Bilde": ""
  },
  {
    "Navn": "Lekeanlegg Flåm skole",
    "Anleggsklasse": "Lekeanlegg",
    "Anleggskategori": "Lekeanlegg",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.1185955583453,
    "Breddegrad": 60.8429557422547,
    "Eier": "Aurland kommune",
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Park Lunden",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Park",
    "Anleggstype": "Park",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.11243760280931,
    "Breddegrad": 60.8518528510741,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "Enkel park. Benker og grønt areal + fredet bauta",
    "Bilde": "bilder/park_Flam.jpg"
  },
  {
    "Navn": "Badekai",
    "Anleggsklasse": "Nærmiljøanlegg",
    "Anleggskategori": "Lekeanlegg i tilknyttning skole",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.11672971846639,
    "Breddegrad": 60.864686296761,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "Lekeanlegg ABU",
    "Anleggsklasse": "Lekeanlegg",
    "Anleggskategori": "Lekeanlegg i tilknyttning skole",
    "Anleggstype": NaN,
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.19685071412431,
    "Breddegrad": 60.9033164911873,
    "Eier": "Aurland kommune",
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b1",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18027567791124,
    "Breddegrad": 60.9034360891704,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b1.jpg"
  },
  {
    "Navn": "b2",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.1810157080574,
    "Breddegrad": 60.9034396044549,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b2.jpg"
  },
  {
    "Navn": "b3",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18182480392657,
    "Breddegrad": 60.9033294340663,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b3.jpg"
  },
  {
    "Navn": "b4",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18435613036217,
    "Breddegrad": 60.9040247579721,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b4.jpg"
  },
  {
    "Navn": "b5",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.187296374228,
    "Breddegrad": 60.9058724593991,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b5.jpg"
  },
  {
    "Navn": "b6",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18667499527154,
    "Breddegrad": 60.9058800394436,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b6.jpg"
  },
  {
    "Navn": "b7",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18660814950171,
    "Breddegrad": 60.9060711484194,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b7.jpg"
  },
  {
    "Navn": "b8",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.1865916824156,
    "Breddegrad": 60.9061789445666,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b8.jpg"
  },
  {
    "Navn": "b9",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18687996486974,
    "Breddegrad": 60.9061162581973,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b9.jpg"
  },
  {
    "Navn": "b10",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18718017161006,
    "Breddegrad": 60.9060044695104,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b11",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18791087948894,
    "Breddegrad": 60.9064734145446,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b11.jpg"
  },
  {
    "Navn": "b12",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18899894960283,
    "Breddegrad": 60.9084452562347,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b12.jpg"
  },
  {
    "Navn": "b13",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18878540707527,
    "Breddegrad": 60.9085679403977,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b14",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18934121373037,
    "Breddegrad": 60.908400742712,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b14.jpg"
  },
  {
    "Navn": "b15",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18914734104297,
    "Breddegrad": 60.9097673771513,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b15.jpg"
  },
  {
    "Navn": "b16",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18931992969403,
    "Breddegrad": 60.9114645695978,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b16.jpg"
  },
  {
    "Navn": "b17",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18970900113345,
    "Breddegrad": 60.9108374459073,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b18",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18885087087277,
    "Breddegrad": 60.9059073257022,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b18.jpg"
  },
  {
    "Navn": "b19",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18875998659554,
    "Breddegrad": 60.9057265891161,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b19.jpg"
  },
  {
    "Navn": "b20",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18864944682645,
    "Breddegrad": 60.9057361792534,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b21",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18950178186755,
    "Breddegrad": 60.9057033893291,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b21.jpg"
  },
  {
    "Navn": "b22",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18941656193921,
    "Breddegrad": 60.905795913438,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b22.jpg"
  },
  {
    "Navn": "b23",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18760891479363,
    "Breddegrad": 60.9056750197464,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b23.jpg"
  },
  {
    "Navn": "b24",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18717824365278,
    "Breddegrad": 60.905641963219,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b24.jpg"
  },
  {
    "Navn": "b25",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.1857107910141,
    "Breddegrad": 60.9065065333848,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b26",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18536858779226,
    "Breddegrad": 60.9063926682065,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b27",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18511676775666,
    "Breddegrad": 60.9062630434335,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b28",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18480857396669,
    "Breddegrad": 60.9060976082557,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b29",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18439042849318,
    "Breddegrad": 60.905870218443,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b29.jpg"
  },
  {
    "Navn": "b30",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18412947723905,
    "Breddegrad": 60.9056235888022,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b31",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.1856076562156,
    "Breddegrad": 60.9063000557563,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b31.jpg"
  },
  {
    "Navn": "b32",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18253555385105,
    "Breddegrad": 60.9045440096967,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": "bilder/b32.jpg"
  },
  {
    "Navn": "b33",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18143444794031,
    "Breddegrad": 60.9040892100246,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b34",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18811264013927,
    "Breddegrad": 60.9052043013923,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  },
  {
    "Navn": "b35",
    "Anleggsklasse": "Benk",
    "Anleggskategori": "Benk",
    "Anleggstype": "Benk",
    "Byggeår": null,
    "Siste ombyggingsår": null,
    "Lengdegrad": 7.18735904619952,
    "Breddegrad": 60.9051523499917,
    "Eier": NaN,
    "Drifter": NaN,
    "Planlagt": false,
    "Kommentar": "",
    "Bilde": ""
  }
];
